[[section]]
name = ".segment"
rom = 0x00001000
vram = 0x80000400
size = 0xA3AA0

symbols = [
    { name = "gLoadedDLLList", vram = 0x800A7D10 },
    { name = "gLoadedDLLCount", vram = 0x800A7D14 },
    { name = "gFile_DLLS_TAB", vram = 0x800a7d18 },
]
