id: io.github.francessco121.dino_recomp
runtime: org.freedesktop.Platform
runtime-version: "24.08"
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.llvm19
command: DinosaurPlanetRecompiled
finish-args:
  - "--socket=wayland"
  - "--socket=fallback-x11"
  - "--socket=pulseaudio"
  # TODO: switch from all to dri,input when most users are on flatpak >=1.15.6
  - "--device=all"
  #- "--device=dri"
  #- "--device=input"
  - "--filesystem=xdg-config"
modules:
  - name: DinosaurPlanetRecompiled
    buildsystem: simple
    build-commands:
      # Build N64/RSP Recomp
      - "cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_MAKE_PROGRAM=ninja -G Ninja -S lib/N64Recomp -B lib/N64Recomp/cmake-build"
      - "cmake --build lib/N64Recomp/cmake-build --config Release --target N64Recomp --parallel"
      - "cmake --build lib/N64Recomp/cmake-build --config Release --target RSPRecomp --parallel"
      - "cp lib/N64Recomp/cmake-build/N64Recomp N64Recomp"
      - "cp lib/N64Recomp/cmake-build/RSPRecomp RSPRecomp"
      - "./N64Recomp dino.toml"
      - "./RSPRecomp aspMain.toml"
      # Build DinosaurPlanetRecompiled
      - "cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_MAKE_PROGRAM=ninja -DPATCHES_C_COMPILER=clang -DPATCHES_LD=ld.lld -DRECOMP_FLATPAK=ON -G Ninja -S . -B cmake-build"
      - "cmake --build cmake-build --config Release --target DinosaurPlanetRecompiled --parallel"
      # Install
      - "rm -rf assets/scss"
      - "mkdir -p /app/bin"
      - "cp cmake-build/DinosaurPlanetRecompiled /app/bin/DinosaurPlanetRecompiled"
      - "cp gamecontrollerdb.txt /app/bin/gamecontrollerdb.txt"
      - "cp -R assets /app/bin/assets"
      - "install -Dm644 icons/64.png /app/share/icons/hicolor/64x64/apps/${FLATPAK_ID}.png"
      - "install -Dm644 deploy/io.github.francessco121.dino_recomp.metainfo.xml /app/share/metainfo/${FLATPAK_ID}.metainfo.xml"
      - "install -Dm644 deploy/io.github.francessco121.dino_recomp.desktop /app/share/applications/${FLATPAK_ID}.desktop"
    sources:
      - type: dir
        path: "../../"
    build-options:
      append-path: "/usr/lib/sdk/llvm19/bin"
      prepend-ld-library-path: "/usr/lib/sdk/llvm19/lib"
      build-args:
        - "--share=network"
